-- LIST CONTRAINTS 
-- ------------------
-- FK
-- FK POINTING TO ME
-- PK
-- UK
-- ------------------

SELECT
    C.CONSTRAINT_TYPE AS "CONSTRAINT_TYPE",
    K.TABLE_SCHEMA AS "CHILD_TABLE_SCHEMA",
    K.TABLE_NAME AS "CHILD_TABLE",
    K.COLUMN_NAME AS "CHILD_TABLE_COLUMN",
    K.CONSTRAINT_NAME AS "CONSTRAINT_NAME",
    CASE
        WHEN C.CONSTRAINT_TYPE = 'FOREIGN KEY' THEN '-->'
        ELSE ''
    END AS "",
    K.REFERENCED_TABLE_SCHEMA AS "PARENT_TABLE_SCHEMA",
    K.REFERENCED_TABLE_NAME AS "PARENT_TABLE",
    K.REFERENCED_COLUMN_NAME AS "PARENT_TABLE_COLUMN"
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE K
    INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS C ON K.CONSTRAINT_SCHEMA=C.CONSTRAINT_SCHEMA
        AND K.CONSTRAINT_NAME=C.CONSTRAINT_NAME 
        AND K.TABLE_SCHEMA=C.TABLE_SCHEMA
        AND K.TABLE_NAME=C.TABLE_NAME
WHERE 
    'unipay' IN (K.TABLE_SCHEMA,K.REFERENCED_TABLE_SCHEMA)           -- SCHEMA
    AND 'payouts_process_audit' IN (K.TABLE_NAME,K.REFERENCED_TABLE_NAME)       -- TABLE 
ORDER BY 1,6,7,2,3;