-- VISTAS
SELECT TABLE_SCHEMA, TABLE_NAME, DEFINER FROM INFORMATION_SCHEMA.VIEWS WHERE DEFINER not in ('mysql.sys@localhost','rdsadmin@localhost') \G

-- TRIGGERS
SELECT TRIGGER_SCHEMA, TRIGGER_NAME, DEFINER FROM INFORMATION_SCHEMA.TRIGGERS WHERE DEFINER not in ('mysql.sys@localhost','rdsadmin@localhost') \G

-- EVENTOS
SELECT EVENT_SCHEMA, EVENT_NAME, DEFINER FROM INFORMATION_SCHEMA.EVENTS WHERE DEFINER not in ('mysql.sys@localhost','rdsadmin@localhost') \G

-- PROCEDURES
SELECT ROUTINE_SCHEMA, ROUTINE_NAME, DEFINER FROM INFORMATION_SCHEMA.ROUTINES WHERE DEFINER not in ('mysql.sys@localhost','rdsadmin@localhost') \G
