SELECT
  TABLE_NAME AS `Tabla`,
  ROUND((DATA_LENGTH) / 1024 / 1024 / 1024) AS "DATA (MB)",
  ROUND((INDEX_LENGTH) / 1024 / 1024 / 1024) AS "INDEX (MB)",
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024 / 1024) AS "TOTAL (MB)"
FROM
  information_schema.TABLES
WHERE
  TABLE_SCHEMA = "unipay"
ORDER BY
  (DATA_LENGTH + INDEX_LENGTH)
DESC limit 10;

SELECT table_name, table_rows
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'unipay'
    ORDER BY table_rows DESC
    LIMIT 10;